#! /usr/bin/env bash
# Spell check with suggestions for the currently focused acme-window

WINID="$(echo "active / ." | nc localhost 2009)"
(( WINID > 0 )) || exit 1

fname="$(basename "$(9p read "acme/$WINID/tag" | cut -d' ' -f1)")"
body="$(9p read "acme/$WINID/body")"
errors="$(echo "$body" | aspell -a 2>&1 | grep -E '^&' | tr -d ':')"

echo "$errors" | while read -r line ; do
  mistake="$(echo "$line" | cut -d' ' -f2)"
  suggestions="$(echo "$line" | cut -d' ' -f5,6,7 | tr -d ',')"

  # print one line per mistake
  echo "$body" | grep -n "$mistake" | cut -d':' -f1 |  while read -r lnum ; do
    echo -e "$fname:$lnum\t$mistake -- $suggestions"
  done
done