#!/bin/bash
# Start the acme text editor and some related helper utilities

case "$(uname)" in
    Linux)
        # font="/mnt/font/TerminessTTFNerdFontComplete-Medium/10a/font"
        font="/mnt/font/ProFontForPowerline/10a/font"
        ;;
    Darwin)
        # font="/mnt/font/TerminessTTFNerdFontComplete-Medium/12a/font"
        font="/mnt/font/ProFontForPowerline/14a/font"
        ;;
esac

export PATH=$PATH:$PLAN9/bin
export MANPATH=$MANPATH:$PLAN9/man
export SHELL=rc

pgrep plumber || plumber &

if [ -f "$PLUMBFILE" ]; then
	cat "$PLUMBFILE" | 9p write plumb/rules
else
	cat $PLAN9/plumb/basic | 9p write plumb/rules
fi

acme -f $font &
sleep 1  # wait for acme to come up
snoop-acme &
